// burger-constructor
export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN';
export const ADD_INGREDIENT: 'ADD_INGREDIENT' = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT: 'DELETE_INGREDIENT' = 'DELETE_INGREDIENT';
export const MOVE_INGREDIENT: 'MOVE_INGREDIENT' = 'MOVE_INGREDIENT';

// test
export const TEST: "TEST" = "TEST";

// burger-ingredients
export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED';
export const SHOW_INGREDIENT_DETAIL: 'SHOW_INGREDIENT_DETAIL' = 'SHOW_INGREDIENT_DETAIL';
export const HIDE_INGREDIENT_DETAIL: 'HIDE_INGREDIENT_DETAIL' = 'HIDE_INGREDIENT_DETAIL';


// make-order
export const MAKE_ORDER_REQUEST: 'MAKE_ORDER_REQUEST' = 'MAKE_ORDER_REQUEST';
export const MAKE_ORDER_SUCCESS: 'MAKE_ORDER_SUCCESS' = 'MAKE_ORDER_SUCCESS';
export const MAKE_ORDER_FAILED: 'MAKE_ORDER_FAILED' = 'MAKE_ORDER_FAILED';
export const HIDE_ORDER_DETAIL: 'HIDE_ORDER_DETAIL' = 'HIDE_ORDER_DETAIL';

// tabs
export const SWITCH_TAB: 'SWITCH_TAB' = 'SWITCH_TAB';

// user
export const REGISTER_REQUEST: 'REGISTER_REQUEST' = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS: 'REGISTER_SUCCESS' = 'REGISTER_SUCCESS';
export const REGISTER_FAILED: 'REGISTER_FAILED' = 'REGISTER_FAILED';

export const LOGIN_REQUEST: 'LOGIN_REQUEST' = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';
export const LOGIN_FAILED: 'LOGIN_FAILED' = 'LOGIN_FAILED';

export const LOGOUT_REQUEST: 'LOGOUT_REQUEST' = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED: 'LOGOUT_FAILED' = 'LOGOUT_FAILED';

export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS'
export const GET_USER_FAILED: 'GET_USER_FAILED' = 'GET_USER_FAILED'

export const FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST' = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS' = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILED: 'FORGOT_PASSWORD_FAILED' = 'FORGOT_PASSWORD_FAILED';

export const RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST' = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS' = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED' = 'RESET_PASSWORD_FAILED';

export const PATCH_USER_REQUEST: 'PATCH_USER_REQUEST' = 'PATCH_USER_REQUEST'
export const PATCH_USER_SUCCESS: 'PATCH_USER_SUCCESS' = 'PATCH_USER_SUCCESS'
export const PATCH_USER_FAILED: 'PATCH_USER_FAILED' = 'PATCH_USER_FAILED'


// get-order
export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAILED: 'GET_ORDER_FAILED'= "GET_ORDER_FAILED";


// feed-ws
export const ORDERS_ALL_START: 'ORDERS_ALL_START'  = "ORDERS_ALL_START";
export const ORDERS_ALL_OPEN: 'ORDERS_ALL_OPEN' = "ORDERS_ALL_OPEN";
export const ORDERS_ALL_END: 'ORDERS_ALL_END' = "ORDERS_ALL_END";
export const ORDERS_ALL_SUCCESS: 'ORDERS_ALL_SUCCESS' = "ORDERS_ALL_SUCCESS";
export const ORDERS_ALL_ERROR: 'ORDERS_ALL_ERROR' = "ORDERS_ALL_ERROR";
export const ORDERS_ALL_CLOSED: 'ORDERS_ALL_CLOSED' = "ORDERS_ALL_CLOSED";
export const ORDERS_ALL_MESSAGE: 'ORDERS_ALL_MESSAGE' = "ORDERS_ALL_MESSAGE";

// order-user-ws
export const ORDERS_USER_START = "ORDERS_USER_START";
export const ORDERS_USER_OPEN = "ORDERS_USER_OPEN";
export const ORDERS_USER_END = "ORDERS_USER_END";
export const ORDERS_USER_SUCCESS = "ORDERS_USER_SUCCESS";
export const ORDERS_USER_ERROR = "ORDERS_USER_ERROR";
export const ORDERS_USER_CLOSED = "ORDERS_USER_CLOSED";
export const ORDERS_USER_MESSAGE = "ORDERS_USER_MESSAGE";